# Generated by Django 4.2.7 on 2025-11-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_id', models.CharField(help_text="Unique identifier (e.g., 'django-serializer-001')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=150, unique=True)),
                ('title', models.CharField(help_text='Problem title shown to users', max_length=255)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pro', 'Pro'), ('veteran', 'Veteran')], default='beginner', max_length=20)),
                ('description', models.TextField(help_text='Full problem description (supports Markdown)')),
                ('description_preview', models.CharField(blank=True, help_text='Short preview for problem list', max_length=300)),
                ('context_code', models.TextField(blank=True, help_text='Pre-existing code context (read-only for user)')),
                ('starter_code', models.TextField(blank=True, help_text='Initial code in editor (editable by user)')),
                ('target_area', models.CharField(blank=True, help_text="What part of code to implement (e.g., 'UserSerializer class')", max_length=200)),
                ('validation_spec', models.JSONField(default=dict, help_text='Validation configuration (imports, structure, behavior)')),
                ('import_weight', models.DecimalField(decimal_places=2, default=20.0, help_text='Weight for imports validation (default 20%)', max_digits=4)),
                ('structure_weight', models.DecimalField(decimal_places=2, default=35.0, help_text='Weight for structure validation (default 35%)', max_digits=4)),
                ('behavior_weight', models.DecimalField(decimal_places=2, default=45.0, help_text='Weight for behavior validation (default 45%)', max_digits=4)),
                ('passing_score', models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum score to consider problem solved', max_digits=4)),
                ('hints', models.JSONField(default=list, help_text='Progressive hints as JSON array')),
                ('learning_resources', models.JSONField(default=list, help_text='External learning resources as JSON array')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=30, help_text='Estimated time to solve (in minutes)')),
                ('total_submissions', models.PositiveIntegerField(default=0, help_text='Total number of submissions')),
                ('accepted_submissions', models.PositiveIntegerField(default=0, help_text='Number of accepted submissions')),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Acceptance rate percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether problem is available to users')),
                ('is_premium', models.BooleanField(default=False, help_text='Whether problem requires premium access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.framework')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'ordering': ['framework', 'difficulty', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_id', models.CharField(help_text='Unique identifier for this pattern', max_length=100)),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Standard ModelSerializer')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this solution approach')),
                ('ast_representation', models.JSONField(help_text='AST structure of the pattern')),
                ('behavior_signature', models.JSONField(default=dict, help_text='Expected behavior characteristics')),
                ('example_code', models.TextField(blank=True, help_text='Example code that matches this pattern')),
                ('required_imports', models.JSONField(default=list, help_text='List of required imports')),
                ('required_structure', models.JSONField(default=dict, help_text='Required code structure elements')),
                ('forbidden_patterns', models.JSONField(default=list, help_text='Patterns that should not be present')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the recommended solution pattern')),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=85.0, help_text='Minimum match confidence to accept (0-100)', max_digits=4)),
                ('match_count', models.PositiveIntegerField(default=0, help_text='Number of submissions matching this pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['-is_primary', 'pattern_id'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['framework', 'difficulty'], name='problems_pr_framewo_53a176_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['problem_id'], name='problems_pr_problem_1cf950_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='problems_pr_slug_19f4ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pattern',
            unique_together={('problem', 'pattern_id')},
        ),
    ]
