# Generated by Django 4.2.7 on 2025-11-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(help_text="User's submitted code")),
                ('language', models.CharField(default='python', help_text='Programming language (python, javascript)', max_length=50)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('partially_passed', 'Partially Passed'), ('failed', 'Failed'), ('syntax_error', 'Syntax Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall score (0-100)', max_digits=5)),
                ('validation_results', models.JSONField(default=dict, help_text='Detailed breakdown of validation (imports, structure, behavior)')),
                ('feedback', models.JSONField(default=list, help_text='Array of feedback messages with line numbers')),
                ('matched_patterns', models.JSONField(default=list, help_text='Patterns that were matched with confidence scores')),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Validation execution time in milliseconds')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints viewed before this submission')),
                ('hint_indices', models.JSONField(default=list, help_text='Which hints were viewed (array of indices)')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt this is for this user-problem combination')),
                ('is_disputed', models.BooleanField(default=False, help_text='User claims this should be accepted')),
                ('dispute_reason', models.TextField(blank=True, help_text="User's reason for disputing the verdict")),
                ('dispute_resolved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text='When validation completed', null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False, help_text='Whether user has successfully solved this problem')),
                ('is_attempted', models.BooleanField(default=False, help_text='Whether user has made at least one attempt')),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total number of submissions')),
                ('best_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Highest score achieved', max_digits=5)),
                ('hints_viewed', models.PositiveIntegerField(default=0, help_text='Number of hints viewed for this problem')),
                ('first_attempt_at', models.DateTimeField(blank=True, help_text='When user first attempted this problem', null=True)),
                ('solved_at', models.DateTimeField(blank=True, help_text='When user first solved this problem', null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, help_text='Most recent submission time', null=True)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'ordering': ['-last_attempt_at'],
                'indexes': [models.Index(fields=['user', 'is_solved'], name='submissions_user_id_a4adbc_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['verdict'], name='submissions_verdict_223995_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submitted_at'], name='submissions_submitt_1f3aca_idx'),
        ),
    ]
