# Generated by Django 4.2.7 on 2025-11-07 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_problems_solved', models.PositiveIntegerField(default=0, help_text='Total number of problems solved')),
                ('total_problems_attempted', models.PositiveIntegerField(default=0, help_text='Total number of problems attempted')),
                ('total_submissions', models.PositiveIntegerField(default=0, help_text='Total number of code submissions')),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Cumulative score across all solved problems')),
                ('beginner_solved', models.PositiveIntegerField(default=0)),
                ('intermediate_solved', models.PositiveIntegerField(default=0)),
                ('pro_solved', models.PositiveIntegerField(default=0)),
                ('veteran_solved', models.PositiveIntegerField(default=0)),
                ('framework_stats', models.JSONField(default=dict, help_text="Problems solved per framework {'django': 10, 'react': 5, ...}")),
                ('current_streak_days', models.PositiveIntegerField(default=0, help_text='Current consecutive days with activity')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, help_text='Longest streak ever achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Last date user solved a problem', null=True)),
                ('preferred_language', models.CharField(default='python', help_text='Preferred programming language', max_length=50)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('bio', models.TextField(blank=True, help_text='User biography', max_length=500)),
                ('github_username', models.CharField(blank=True, help_text='GitHub username', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_index', models.PositiveIntegerField(help_text='Index of the hint viewed (0-based)')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usage', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hint Usage',
                'verbose_name_plural': 'Hint Usage',
                'ordering': ['viewed_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='users_hintu_user_id_f4eed3_idx')],
                'unique_together': {('user', 'problem', 'hint_index')},
            },
        ),
    ]
