# Generated by Django 4.2.7 on 2025-11-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal framework name (e.g., 'django', 'react')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name for UI (e.g., 'Django', 'React')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the framework')),
                ('icon_url', models.URLField(blank=True, help_text='URL to framework icon/logo', null=True)),
                ('version', models.CharField(blank=True, help_text="Primary version supported (e.g., '4.2', '18')", max_length=50)),
                ('documentation_url', models.URLField(blank=True, help_text='Link to official documentation', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this framework is currently available for problems')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Framework',
                'verbose_name_plural': 'Frameworks',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal category name (e.g., 'models', 'serializers')", max_length=100)),
                ('display_name', models.CharField(help_text="Display name for UI (e.g., 'Models', 'Serializers')", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of what this category covers')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within framework')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(help_text='Framework this category belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.framework')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['framework', 'order', 'display_name'],
                'unique_together': {('framework', 'name')},
            },
        ),
    ]
